*&---------------------------------------------------------------------*
*& Modulpool SAPBC414_TRAVELAG_SQL_S
*&---------------------------------------------------------------------*


INCLUDE ZTRAVELAG_A12_TTOP.
*INCLUDE BC414_TRAVELAG_SQL_STOP.
INCLUDE ZTRAVELAG_A12_TF01.
*INCLUDE BC414_TRAVELAG_SQL_SF01.
INCLUDE ZTRAVELAG_A12_TO01.
*INCLUDE BC414_TRAVELAG_SQL_SO01.
INCLUDE ZTRAVELAG_A12_TL01.
*INCLUDE BC414_TRAVELAG_SQL_SI01.
INCLUDE ZTRAVELAG_A12_TE01.
*INCLUDE BC414_TRAVELAG_SQL_SE01.
